[package]
name = "challenge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "2"
rand = "0.7"
rayon = "1"
byteorder = "1"
num-traits = "0.2"
num-derive = "0.3"